* Tim Spier - Populismus und Modernisierung
:PROPERTIES:
:NOTER_DOCUMENT: Spier_2006__Populismus_und_Modernisierung.pdf
:END:
** Einleitung
:PROPERTIES:
:NOTER_PAGE: (1 . 0.5927835051546392)
:END:
- Populismus ist vielseitiger, komplexer und verbreiteter als es erste Annahmen vermuten lassen
  - um derartig unterschiedliche Entscheidungsformen unter einem Oberbegriff zu klassifizieren müssen etwaige Gemeinsamkeiten vorliegen, um dies zu Rechtfertigen
- These des Autors: Gemeinsamkeit liegt darin, dass jene pop. Parteien und Bewegunen eine Reaktion auf Krisen im Gefolge  von gesellschaftlichen Modernisierungsprozessen darstellen
  - gesellschaftl. Modernisierungsprozesse (und/oder gravierende ökon., kulturelle wie auch pol. Veränderungen) bringen Verwerfungen & Umbrüche mit sich, welche in Bevölkerung Ängste & Unsicherheit hervorrufen, die widerrum in Unzufriedenheit & Protest umschlagen können
    - -> bietet gute Voraussetzungen fuer pop Mobilisierung
** Populismus und Modernisierung - Zwei Seiten einer Medaille
*** Definition & Wirkung von Modernisierung
:PROPERTIES:
:NOTER_PAGE: (2 . 0.21735395189003437)
:END:
- Modernisierung = Entwicklung einer Gesellschaft von einem älteren Zustand in einen neuen
- Populismus als Folge von Modernisierungsprozessen
  - Konsequenzen der Moderne (pos/neg Auswirkungen) auf bestimmte Individuen/Bevölkerungsgruppen
- Modernisierung als reine Analysekategorie, die unterschiedlichste Formen und Ausprägungen annehmen kann
- Modernisierung ist kein neutraler oder ausschließlich positiver/negativer Prozess, da es immer Gewinner/Verlierer gibt, meist:
  - Gewinner = Bevölkerungsgruppen, die sich an die stattfindenen Veränderungen am besten anpassen
  - Verlierer = die, die sich nicht ohne weiteres anpassen (können) oder durch den Wandel negativ betroffen sind
- Verlierer des Modernisierungsprozesses bieten Voraussetzungen für pol Protest: allg. Unzufriedenheit -> pol Unzufriedenheit -> Politikverdrossenheit
- schwerwiegender als Unzufriedenheit sind einhergehende psych. Probleme, die aus der sozialen Situation von Modernisierungsverlierer resultieren können (tiefgreifende Verunsicherungen)
*** Warum profitieren ausgerechnet populistische Bewegungen von Unzufriedenheit?
:PROPERTIES:
:NOTER_PAGE: (4 . 0.7903780068728522)
:END:
- These: Populistische Agitation spricht Modernisierungsverlierer besonders an

Merkmale des Populismus:
1. Appell an "das Volk" oder "den kleinen Mann"
  - das Volk (populus) wird als mehr oder weniger homogene Masse angesprochen und Unterschiede weitgehend geleugnet
  - Zuschreibung pos. Eigenschaften an das Volk zur Vermittlung eines Zugehörigkeitgefühls und einer sozialen Identität
2. Gegenüberstellung zur (homogenen) "Elite"/"Establishment", welche ebenfalls sehr klischeehaft stigmatisiert wird
3. charismatische Führerfiguren, die sich zu "Volksvertretern" hochstilisieren
4. Vornahme einer Abgrenzung von bestimmten Bevölkerungsgruppen (insb. Minderheiten)

Einschränkung: Nicht immer folgt auf Modernisierungsprozesse ein Erfolg von Populisten, es ist ausreichendes Potential von Nöten:
- Verdichtung negativer Folgen von Modernisierungsprozessen zu einer krisenhaften Situation
  - erst dieser "populistische Moment" schafft Raum zur Mobilisierung
  - schafft Gelegenheitsfenster, dass auch genutzt werden muss
- auch etablierte Parteien können Themen aufgreifen und somit das Potential an sich binden
- Populisten müssen ihr Potential durch Massenmedien o eigene Propaganda effektiv ausspielen
  - effektive Hervorbringung ihrer ressentimentgeladenen Rhetorik
- rhetorisch geschickte Führerfigur
** Historische Beispiele für den Zusammenhang von Populismus & Modernisierung
:PROPERTIES:
:NOTER_PAGE: 7
:END:
*** Populisten Bewegung in den USA
:PROPERTIES:
:NOTER_PAGE: 8
:END:
- durch Industrialisierung (Ende des 19.Jhd), die viele Monopole im Nordosten hervorbrachte, fühlten sich Farmer und Siedler des Mittleren Westens und Südens zunehmend abgehängt und gerieten in Abhängigkeiten verschiedenster Natur
- diese beklemmende wirtschaftliche Situation der Farmer mündete in *organisierten Protest*
- Granger-Bewegung (propagierte Selbsthilfemaßnahmen) -> Greenback-Party (Abschaffung des Goldstandards; erzielte einige Wahlerfolge) -> /Farmers' Alliance/ (zunächst Selbsthilfestrategie, dann *aktiver politischer Protest* zB gemeinschaftlicher Boykott von Monopolkonzernen)

Demokraten & Republikaner beachteten die Forderungen der Farmers' Alliance nicht und so wurde die *People's Party* (später auch /Populist Party/ genannt) gegründet um selbst bei Wahlen anzutreten
**** Forderungen und Erfolge der People's Party
:PROPERTIES:
:NOTER_PAGE: (9 . 0.1288782816229117)
:END:
Erfolge gingen nach der Jahrhundertwende zurück, weil Protestbereitschaft der Farmer während des Konjunkturaufschwungs sank und viele pol. Forderungen von den großen Parteien aufgegriffen worden waren

**** Typische Merkmale
:PROPERTIES:
:NOTER_PAGE: (9 . 0.3866348448687351)
:END:
Farmers' Alliance und Peoples Party wiesen wesentliche Merkmale populistischer Bewegungen auf:
- setzten Potential der durch Modernisierungsprozesse negativ betroffener Farmer um
- typisch idealisiertes Volksverständnis; Beschwörung des "common man" & hart arbeitenden Farmers; I
  - "einfache Leute" (Süden, Mittlerer Westen) vs wirtschaftl./pol. Eliten der Ostküste
- mehrere Agitatoren die rhetorisch begabt und mit charismatischen Qualitäten ausgestattet waren (allerdings keine überragende Führerfigur)
- charakteristische ressentimentgeladene Abgrenzung ggü versch. Bevölkerungsgruppen (Bänker, Finanziers, Juden, Schwarze)
  - Mischung progressiver Forderungen mit autoritären Ideologieelementen
*** Die Narodniki in Russland
:PROPERTIES:
:NOTER_PAGE: 10
:END:
Narodniki (zu deutsch Volkstümer/Volksfreunde) waren eine Gruppe radikaler Intellektueller, die Unterstützung im Volk suchten
- eher ein Besipiel des Scheiterns einer populistischen Bewegung

Situation in Russland:
- ländliche Bevölkerung des 19.Jhd. in starker Abhängigkeit von Grundherren
  - finanzielle abhängig und rechtlich benachteiligt
- rasanter Anstieg der Bevölkerung ohne verbesserte landwirtschaftl. Erträge führte zu *Armut* und *verbitterter Stimmung*
  
Trotz dieses vermeindlich großen Potentials für Populismus durch Modernisierungsprozesse, blieb dieser zunächst aus. Es kam nicht zu größeren Unruhen und Organisationsversuche der Bauern waren im Wesentlichen nicht vorhanden.

In den 1870ern zogen dann Tausende junger Studenten, welche sich als Vollstrecker romantisierender Leitgedanken (Zukunft Russlands liegt bei den Bauern) intellektueller Vordenker sahen, aufs Land. Sie versuchten die Bauern vergeblich für revolutionäre Aktivitäten zu gewinnen.
- die städtischen Intellektuellen waren den Bauern fern/fremd
- Sympathie für den Zaren war auf dem Land noch immer groß

Ergo führe ein "populistischer Moment" nicht automatisch zum Erfolg einer populistischen Bewegung
*** Populismus in der Weimarer Republik
:PROPERTIES:
:NOTER_PAGE: (11 . 0.6587112171837709)
:END:
1. Abhängung und soziale Isolierung des alten Mittelstandes
2. Händler & Kleingewerbebetreibenden zunehmend enttäuscht von Politik und etablierten Parteien (sowie bürgerlichen Parteien)
3. Proteste durch lokale und regionale Vereinigungen, sowie spontan einberufene Versammlungen
4. Bildung von freien Fachverbänden, die nich an offizelle Dachverbände angeschlossen waren

Bei Wahlen kam es dann vermehrt Achtungserfolgen von kleinen Splitterparteien, die sich in radikaler Weise dem Mittelstand verschrieben hatten. Anfang der 30er gelang es dann der NSDAP den alten Mittelstand zunehmend an sich zu binden.
*** Typische Merkmale
:PROPERTIES:
:NOTER_PAGE: 14
:END:
- Beschwörung des kleinen Mannes und des gesunden Mittelstandes
- Hochstilisierung des Mittelstandes zum ideellen Kern des Volkes
- radikale Kritik der pol. Eliten
- Abgrenzung ggü anderen Bevölkerungsgruppen (Unternehmer, Großkapital)
  - Kampagnen gegen Warenhäuser und Konsumgemeinschaften, welche in Konkurrenz zu kleinen Händlern des Mittelstandes standen
  - antisemitisch aufgeladene Kampagnen gegen jüdische Warenhäuser
- vor Hitler allerdings keine charismatische Führerfigur
** Rechtspopulismus als Schattenseite aktueller Modernisierungsprozesse
:PROPERTIES:
:NOTER_PAGE: 15
:END:
- seit Mitte der 1980er kann in vielen westlichen Industrienationen der Aufstieg "rechtspopulistischer Parteien" beobachtet werden
