* Tim Spier - Populismus und Modernisierung
:PROPERTIES:
:NOTER_DOCUMENT: Spier_2006__Populismus_und_Modernisierung.pdf
:END:
** Einleitung
:PROPERTIES:
:NOTER_PAGE: (1 . 0.5927835051546392)
:END:
- Populismus ist vielseitiger, komplexer und verbreiteter als es erste Annahmen vermuten lassen
  - um derartig unterschiedliche Entscheidungsformen unter einem Oberbegriff zu klassifizieren müssen etwaige Gemeinsamkeiten vorliegen, um dies zu Rechtfertigen
- These des Autors: Gemeinsamkeit liegt darin, dass jene pop. Parteien und Bewegunen eine Reaktion auf Krisen im Gefolge  von gesellschaftlichen Modernisierungsprozessen darstellen
  - gesellschaftl. Modernisierungsprozesse (und/oder gravierende ökon., kulturelle wie auch pol. Veränderungen) bringen Verwerfungen & Umbrüche mit sich, welche in Bevölkerung Ängste & Unsicherheit hervorrufen, die widerrum in Unzufriedenheit & Protest umschlagen können
    - -> bietet gute Voraussetzungen fuer pop Mobilisierung
** Populismus und Modernisierung - Zwei Seiten einer Medaille
*** Definition & Wirkung von Modernisierung
:PROPERTIES:
:NOTER_PAGE: (2 . 0.21735395189003437)
:END:
- Modernisierung = Entwicklung einer Gesellschaft von einem älteren Zustand in einen neuen
- Populismus als Folge von Modernisierungsprozessen
  - Konsequenzen der Moderne (pos/neg Auswirkungen) auf bestimmte Individuen/Bevölkerungsgruppen
- Modernisierung als reine Analysekategorie, die unterschiedlichste Formen und Ausprägungen annehmen kann
- Modernisierung ist kein neutraler oder ausschließlich positiver/negativer Prozess, da es immer Gewinner/Verlierer gibt, meist:
  - Gewinner = Bevölkerungsgruppen, die sich an die stattfindenen Veränderungen am besten anpassen
  - Verlierer = die, die sich nicht ohne weiteres anpassen (können) oder durch den Wandel negativ betroffen sind
- Verlierer des Modernisierungsprozesses bieten Voraussetzungen für pol Protest: allg. Unzufriedenheit -> pol Unzufriedenheit -> Politikverdrossenheit
- schwerwiegender als Unzufriedenheit sind einhergehende psych. Probleme, die aus der sozialen Situation von Modernisierungsverlierer resultieren können (tiefgreifende Verunsicherungen)
*** Warum profitieren ausgerechnet populistische Bewegungen von Unzufriedenheit?
:PROPERTIES:
:NOTER_PAGE: (4 . 0.7903780068728522)
:END:
- These: Populistische Agitation spricht Modernisierungsverlierer besonders an

Merkmale des Populismus:
1. Appell an "das Volk" oder "den kleinen Mann"
  - das Volk (populus) wird als mehr oder weniger homogene Masse angesprochen und Unterschiede weitgehend geleugnet
  - Zuschreibung pos. Eigenschaften an das Volk zur Vermittlung eines Zugehörigkeitgefühls und einer sozialen Identität
2. Gegenüberstellung zur (homogenen) "Elite"/"Establishment", welche ebenfalls sehr klischeehaft stigmatisiert wird
3. charismatische Führerfiguren, die sich zu "Volksvertretern" hochstilisieren
4. Vornahme einer Abgrenzung von bestimmten Bevölkerungsgruppen (insb. Minderheiten)

Einschränkung: Nicht immer folgt auf Modernisierungsprozesse ein Erfolg von Populisten, es ist ausreichendes Potential von Nöten:
- Verdichtung negativer Folgen von Modernisierungsprozessen zu einer krisenhaften Situation
  - erst dieser "populistische Moment" schafft Raum zur Mobilisierung
  - schafft Gelegenheitsfenster, dass auch genutzt werden muss
- auch etablierte Parteien können Themen aufgreifen und somit das Potential an sich binden
- Populisten müssen ihr Potential durch Massenmedien o eigene Propaganda effektiv ausspielen
  - effektive Hervorbringung ihrer ressentimentgeladenen Rhetorik
- rhetorisch geschickte Führerfigur
** Historische Beispiele für den Zusammenhang von Populismus & Modernisierung
:PROPERTIES:
:NOTER_PAGE: 7
:END:
*** Populisten Bewegung in den USA
