* Who Gets into the Papers? Party Campaign Messages and the Media
:PROPERTIES:
:NOTER_DOCUMENT: Meyer_et_al_2017.pdf
:END:
###
Frage 1: Vernachlässigung (Erfolgsfaktoren) davon wie etwas hingelangt was bisher nicht in Medien präsent sind
Frage 2: ist das kein widerspruch das neue themen erfolgreicher sind steht im konlfikt seite 7 über these 3
** Einleitung
*** Anliegen des Papers
:PROPERTIES:
:NOTER_PAGE: 1
:END:
- Parteien und Politiker generieren "media coverage" und erreichen dadurch Wähler
- Untersuchungsgegenstand des Textes: Inwiefern beeinflussen Attribute im Hinblick auf den Inhalt und Sender von Parteinachrichten die Wahrscheinlichkeit mediale Aufmerksamkeit zu generieren/erhalten
- These: Parteimitteilungen landen mit erhöhter Wahrscheinlichkeit in den Nachrichten, wenn sie in Relation zu Belangen stehen, die bereits Signifikanz in den Medien oder für andere Parteien haben
  - warum: kann evtl. kleineren/low-profile (Oppositions)Parteien helfen Medienaufmerksamkeit zu generien

*** Medieninteresse und Agenda Setting
:PROPERTIES:
:NOTER_PAGE: (1 . 0.6004901960784315)
:END:
- pol. Akteure setzen in Wahlkampagnen die breitere Agenda und Medien antworten/reagieren darauf - nicht andersrum
- die mediale Vermittlung bestimmter Nachrichten zu erzielen ist für die Parteien schwerer als das allgemeine Agenda Setting:
  - mediale Aufmerksamkeit ist knappe/begrenzte Ressource um die Parteien ringen
  - Vermittlung spezifischer Nachrichten hängt von Entscheidungen ab die Journalisten und Editoren treffen

*** Vermittlung spezifischer Nachrichten durch Medien
:PROPERTIES:
:NOTER_PAGE: (2 . 0.30637254901960786)
:END:
- Nachrichteninhalt spielt entscheidene Rolle (für alle pol Akteure):
  - pol. Akteure sollten in der Lage sein die Wahrscheinlichkeit von media coverage durch die Fokussierung auf Themen, die dem Wähler, anderen Parteien oder den Medien wichtig sind, zu erhöhen
- mächtige Politiker können einfacher Medieninteresse erwecken

=> pol Akteure können durch strategische Themenauswahl die Wahrscheinlich von Medienaufmerksamkeit erhöhen

- es ist einfacher Nachrichten die im Kontext von bereits medial erfassten Themen zu verbreiten
  - Macht der Medien vllt größer als man bislang vermutete?
  - ergo ist es schwerer für weniger bekannte pol Akteure mediale Aufmerksamkeit im Hinblick auf innovative, systemdestabilisierende Nachrichten zu erzeugen
*** Untersuchung österreichischer Berichterstattungen 
:PROPERTIES:
:NOTER_PAGE: 3
:END:
- 16% aller Parteipressemitteilungen erhalten mediale Aufmerksamkeit
  - rel hoch wenn man bedenkt wieviele Pressemitteilungen herausgegeben wird und wie günstig dies ist

** Existing Research on Media Attention to Party Communication
:PROPERTIES:
:NOTER_PAGE: 4
:END:
1. Agenda Setting Studien
- bringt Aufschluss darüber, inwiefern die mediale Agenda mit der parteilichen Agenda übereinstimmt
- Limitierungen:
  - kein Aufschluss über *spezifische, individuelle* Kampagnennachrichten und die Wahrscheinlichkeit, dass sie medial aufgegriffen werden
  - kein Aufschluss darüber, ob die medialen Themen explizit mit einer Partei und ihren Politikern in Verbindung gebracht werden können

2. Media Research
- untersucht inwiefern Medien pol Akteure (Parteien, Politiker) behandelt
  - einige Studien untersuchen darüberhinaus die Rolle pol Akteure (aktiv, passiv)
- pol. Führungspersonen in öffentlicher oder parteivertretender Rolle werden mit höherer Wahrscheinlichkeit in Medien erwähnt
  - aber allein das Auftauchen in Medien ist nicht ausreichend, da es kein Aufschluss darüber gibt, ob/inwiefern pol. Akteure dieses Auftauchen zur Steigerung der Berichterstattung ihrer campaign message nutzen können

** Press Releases as Medium for Campaing Messages
:PROPERTIES:
:NOTER_PAGE: 5
:END:
- Pressemitteilung sind ein Werkzeug pol Akteure um Medien zu erreichen
  - können genutzt werden um zu analysieren, worüber Parteien wollen, dass es in den Medien berichtet wird
  - nützlich für Politiker um Bürger zu erreichen, da evtl vertrauenserweckender als eigene Propaganda/Werbung
- Pressemitteilungen gelten als erfolgreich wenn die Aussagen des Herausgebers/Autors/Partei/Politiker in wenigsten einem Medienbericht, wo der Autor eine aktive Rolle spielt, vorkommen:
  - Erwähnung von Name des Autors oder der Partei als aktiver Sprecher
  - selbe Thematik wie Pressemitteilung
- unerwartete oder wichtige Mitteillungen erreichen, so wie Mitteillungen größerer Parteien, eine Wiedergabe in der Presse mit höherer Wahrscheinlichkeit

** Warum sind Pressemitteilungen einiger Parteien erfolgreicher?
:PROPERTIES:
:NOTER_PAGE: 6
:END:
Erfolgsgründe von Mitteilungen:
- vorherige Medienaufmerksamkeit
- Themen mit high-impact
- evtl Feedback Loop:
  - Politiker äußert sich zu Themen die in den Medien präsent sind, weil sie wissen dass jene Aussagen mit höherer Wahrscheinlichkeit wiedergegeben werden
- Addressierung von Themen die Wählern wichtig sind
  - verläuft beidseitig, da Medien auch beeinflussen was den Wählern wichtig ist
- Themen die neu oder unerwartet sind und bisher weniger diskutiert sind
- Themen die auch für rivalisierende Parteien von Belangen sind
- Themen die einer Partei wichtig sind, landen mit *geringerer* Wahrscheinlichkeit in den Medien

** Data and Methods
:PROPERTIES:
:NOTER_PAGE: 8
:END:
- basierend auf Inhaltsanalysen von 1922 Pressemitteilungen und Zeitungsartikeln im Österreichischen Wahlkampf 2013

*** Unabhängige Variablen
:PROPERTIES:
:NOTER_PAGE: (10 . 0.49167327517842985)
:END:
- Voter Issue Importance (anhand Wählerbefragung)
- Party Issue Importance (anhand Parteienprogramm)
- Party System Issue Importance = Anzahl rivalisierender Parteien die ein Thema addressieren

*** Kontrollvariablen
:PROPERTIES:
:NOTER_PAGE: (11 . 0.4123711340206186)
:END:
- Platzhaltervariable um zwischen Pressemitteilungen von Regierungs- und Nichtregierungsparteien zu unterscheiden
- Klassifizierung des Politikers (Regierungsmitglied, Parteivorsitzender, Ministerpräsident etc)
  - wenn nicht kenntlich, dann Kategorisierung als "Parteiorganisation"
- Variable zur Indikation des Veröffentlichungsdatums (Minuten seit Mitternacht)
- Variable zur Spezifizierung ob eine Mitteilung auf einem externen Geschehen (zb EU Gipfel) basiert
- Messung ob Pressemitteilung im Kontext einer Pressekonferenz steht

*** Abhängige Variable
:PROPERTIES:
:NOTER_PAGE: (12 . 0.3806502775574941)
:END:
Die abhängige Variable gibt an, ob eine Pressemitteilung erfolgreich oder nicht erfolgreich ist

** Ergebnisse
:PROPERTIES:
:NOTER_PAGE: (12 . 0.6344171292624902)
:END:
- 16% der Pressemitteillungen erhalten mediale Aufmerksamkeit
- parties have higher chances of making the news when they address issues that are salient in the media issue agenda.
- Erhöhung der party system issue attention erhöht die mediale Aufmerksamkeit
- Party Issue Importance und Voter Issue Importance konnten keine Wirkung im Hinblick auf mediale Aufmerksamkeit nachgewiesen werden
- nicht signifkant, aber feststellbar: Medien berichten eher weniger über Themen die Teil der hauptsächlichen Kampagne einer Partei sind
- Regierungsmitglieder erhalten höchste Medienaufmerksamkeit, dicht gefolgt von Parteivorsitzenden
- Unterschiede zw Regierungs- und Oppositionspartei ließen sich nicht feststellen
- Externe Ereignisse erhöhen Wahrscheinlichkeit nicht
- lange Pressemitteilungen haben höhere Wahrscheinlichkeit
- nicht signifkant, aber feststellbar: Mitteillungen die früher am Tag veröffentlich werden haben bessere Chancen
  
*Taken together, these results suggest that political actors have higher chances of making the news with messages on issues that are important on the systemic (media or party) level*

** Fazit
:PROPERTIES:
:NOTER_PAGE: 16
:END:
