Vorgehen:
- demokratie index vllt noch weiteren index über die jahre plotten
  - selber plot fuer ein anderes lateinam. land mit inkonsoldiertert demokratie das aber bessere werte hat der unterschied sollte POpulismus an macht sien
    - dafuer von levitsky aus dem buch suchen welches beispiel die hatten was populimsus abgegrenzt hat
  - somit begruenden das demokratie qualität abnahm, dann begruenden das es schon autorative dings ist
- dann aufzeigen wie der populismus konkret dazu gefuehrt hat zum verfall und alles verbinden

To provide a possible explanation for these questions, I argue that Chávez was electorally successful despite deteriorating economic and democratic conditions thanks to the political support he gained and maintained mainly from the Venezuelan poor majority as a result of the achievements of his leftist-populist agenda.  (AUS DIESEM PDF DAS FAZIT IST SEHR GUT)

"The government never went for deep reforms of the society and the economy, but only went for redistribution of wealth. This policy was not enough for the government to face the assault of the Right." (Populistisch)
- Annahme, dass die Leute sind das wichtigste und an ersteer Stelle und tiefgründige Veränderungen der Wirtschaft oä daher nicht notwendig
  
"Corruption is a big problem and like all other left-populist governments, the Maduro government too has treated the issue lightly, given the fact that the oil industry is crucial to Venezuela"

"But the biggest problem is the ambivalence of the Left towards the Maduro government. The Left cannot oppose it, it cannot digest it either. Thus, they say that the Maduro rule is an authoritarian rule based on rental income from oil. Venezuela’s problems are due to populist politics which means squandering away the country’s resources. This logic then leads the Left to argue that it is oversimplification to blame the Right for the ills. By arguing in this manner, the Left is behaving like the Right. It is not pressing for actions against the bankers and the cartels. It is not demanding direct popular controls over a process of restructuration of economy. What is then the difference that remains between the liberals and the Left which is as much enamoured with bourgeois institutionalism as the former? They have forgotten the words ‘class’ and ‘class struggle’."

"The dominant characteristic of populism has been its political expression – certain political specifics. Its economic content is often meagre and when not hollow, it tries to reach welfare to the people without seriously disturbing property relations. "
- typisch Populismus aber fehlerhaft, Geld an das arme Volk etc an erster Stelle aber keine dringend notwendige gesamte Umstrukturierung der Besitze
  
"It is also illegal to fire a worker for basically any reason, including making threats of physical violence against a manager. And, needless to say, it is illegal to set your own prices: The state does that, often setting them below the cost of production, especially for basic goods. Under such circumstances, even "private" firms are in essence state run."
- ruiniert Ökonomie, zielt auf arme Bevolkerung ab (-> populistisch)
  
"aggressive left-wing populism"

"CIA conspiracy"
- andere verantwortlich mahcen
  
- der Populismus hat es erlaubt Chavez an der Macht zu bleiben während er autokraische Sachen durchzog
- am Anfang der Präs. FOkus darauf mehr Macht fuer den PRäs zu bekommen und Wirtschaft unangetastet (mögl. weil populär und Bevolkerung zufrieden aufgrund pump finanzierung)
  - "So he concentrated his first couple of years in consolidating political power. He did not change the economics much. He left the same Finance Minister that [previous President Rafael] Caldera had, Maritza Izaguirre, and there was no discernible change in policies."
- Verabschiedung von 48 Gesetzen die niemand gelesen hat -> dann Proteste -> Then he started blaming the oil company for things, so he ended up trying to mess with the administrative autonomy of the oil company (Feind schuldig machen)
  - the oil company went on strike and he ended up firing 20,000 of the 35,000 employees of the oil company and took over control of that. So at that time he was deeply unpopular. There was a massive political movement against him. And at that time the price of oil started to increase. So his real populist policies started at around 2003, 2004, not in 1999 when he got into power.
- dann Ausgabe von Ölgeldern für massive soziale Programme (warum? verbinden ? vllt um bev zu beschiwchiten, macht zu erhalten)
- insgesamt erhaltungsstrategie durch populistische maneuver aber immer weitere vershclehtertung der demokratie
- So they used exchange controls, price controls, import controls as a way of keeping control on the private sector — as a way of making the private sector pliant and dependent on bureaucratic decisions of the State.
- ökonomischer POpulismus (economic populism) hat ruiniert
- so when you describe for instance his altering the institutions very early on, before he started altering policies, that to me strikes me as a very populist approach. (konnte populist so begruenden das system soowas von geschunden ist deshalb erstmal system anpassung)
- In 1998, Venezuela produced 3.7 million barrels of oil [per day]. Today it’s producing about two. 
- First, all the know-how of that industry, centuries of man-years of experience was lost in the firing of these people (pop. bedingt dadurch verfall der wirtschaft) (viele nach kolumbien geflohen und dort öl boom verursacht)
- They also wanted to create a politically conscious oil company, so they started to put an enormous amount of social programmes and other things on the books of PDVSA, the oil company. And as a consequence they starved the company from investment and they ran the company in an amazingly corrupt way, and this is really not just talk about corruption but evidence of corruption in massive ways.
  - bevolkerung erlebt rise of living standards und laesst es deshalb zu
- das hat die henne zerstoert die die goldene eiers gelegt hat

* Populism and competetive authoritariansm (Levitsky, Loxton)
- "Although populism is commonly viewed as a threat to liberal
democracy,3 the causal mechanisms linking populism to democratic breakdown
remain poorly understood" (Barr’s excellent synthesis)
- "We argue that populist governments push weak democracies
into competitive authoritarianism for at least three reasons."
  - Populisten mangelt es an politischer Erfahrung mit Instutitionen repr. Demokratien
  - Second, due to the anti-establishment nature of their appeal, successful
populists earn an electoral mandate to bury the existing elite and its institutions
  - populist presidents usually confront institutions of horizontal accountability controlled by established parties
- "Lacking experience, facing hostile legislatures and courts, and armed with a mandate to depose the old elite, newly elected populists often assault institutions of horizontal accountability, triggering a constitutional crisis. Presidents who prevail in these showdowns gain unchecked control over state institutions, which allows them to skew the playing field against opponents"
- "Not all democracies with weak institutions and parties decay into competitive authoritarianism. Some additional factor must trigger such transitions; that trigger, we argue, is populism"
- The core message of populist campaigns is that the established elite is corrupt and exclusionary, and that existing regime institutions are therefore not really democratic. Fujimori, Cha´vez, Morales, and Correa all claimed that their countries were “partyarchies” (that is “rule by the parties” rather than by “the people”) and pledged to replace the old elite and its institutions with an “authentic” democracy. Presidential candidates who win on the basis of such appeals earn a mandate to “re-found” the political system. However, the “system” that populists campaign against is representative democracy, and the “corrupt” or “oligarchic” institutions that they pledge to destroy are parties, legislatures, and judiciaries. It is difficult to dismantle such institutions without threatening the democratic regime.
- "Likewise, Venezuela’s authoritarian turn began in 1999, before the oil boom. Thus, although oil rents may have helped Cha´vez consolidate power, it was mass support, not oil revenue, that allowed him to dismantle representative democracy"
  
* A setback for chavez
- Hugo Chávez has since become famous for transforming a flawed but pluralistic democracy into a competitive authoritarian regime
  - Einführung autokratischer Elemente während noch Wahlen existieren
- “statism on steroids” (Etatismus)
- It takes bad policy to accomplish this
- "“Chavenomics”"
- Under Chávez, however, there is overwhelming evidence of Dutch disease
- Nationalizations increased from an annual total of 131 in 2009 to more than 200 in 2010
- Chávez has responded to his party’s declining competitiveness by turning more autocratic, albeit still within bounds
- In his victory speech, Chávez announced one of the most radical state agendas in Venezuelan history. The key planks included a new enabling law that would authorize the president to enact or change more than sixty pieces of legislation without legislative approval .. UND MEHR
- give special powers to chavista citizens’ groups
-  “Bolivarian revolution” war Schlagwort in Wahlkampf (populistisch) und untergräbt jetzt sich selber
- Chávez likes to insist that state intervention in “strategic” industries has been critical to the task of stabilizing prices, but most often his takeovers have been about politics: Nationalizations allow Chávez to court certain labor groups by promising jobs with relaxed productivity standards. This, too, conforms to traditional models of Latin American populism
  

