* The politicization of social divisions in legislative contexts: A dictionary-based analysis of parliamentary questions in the German Bundestag - R.v.Schiller, T. Zittel & M.Henneke

** The significance of social representation

Soziale Repräsentation ist der traditionelle Modus politischer Repräsentation in Westeuropa 

- Parteien repräsentieren sozial zusammenhängende, nationale Wählerkoalitionen -> sozial demokratische Parteien nutzen dieses Model beispielhaft, um Maßnahem für das Werben & Implementieren der Interessen von *blue collar workers (Industriebranche)* 
- Forschungen zweifeln an das Parteien sozial definierte Wähler ansprechen will 
  - Soziostruktureller & Wahlen Veränderung in westlichen Demokratien die zur Schwächung traditioneller von Wähler-Partei Ausrichtung führt (voter-party alignment)
- 2 Szenarien im Bezug auf Parteistrategien 
  - Katz & Mair: Sowie Parteien professioneller werden & mit Institutionen des Staates fusionieren, entziehen sie sich vom Sozialen & somit weniger bereit sich für spezifische soziale Gruppen einzusetzen 
  - Zweitens: In Antwort zu stärker fragmentierten sozialstruktur wird angenommen, dass Parteien den Anreizen der breiten Wählerschaft erliegt, was sie programmatisch ungenau/undeutlich erscheinen macht 
    - Kritik: 	1. Nimmt sozio-deterministische Perspektive an, welche schwer non-lineare temporäre Dynamiken von Parteiaktivitäten & Wählerschaftsverhalten erklären kann 
				2. Spielt *Agency of Parties* herunter, welche aktiv den sozialen & politischen Kontext formen 
				3. Basiert auf schwacher empirischer Grundlage im Bezug auf Parteiverhalten 
- Text zielt darauf Lücken zu füllen, indem Parteistrategien im Vergleich zu sozial definierten Bestandteile untersucht werden 
- neuer Ansatz: Soziale Repräsentation & die deliberative Anstrengungen von Parteien um soziale Divisionen zu politisieren 
- Nutzen dictionary based text analysis, welche einen automatisierten Ansatz für die Konstruktion von dictionaries nutzt 
  - Ansatz beruht auf *comprehensive corpus* von Presseveröffentlichungen von organisierten Interessen als Indikatioren für gruppen spezifische Wünsche 
- in Analyse der repräsentativen Bindungen in Parlamentaren Fragen im Bundestag, kommen sie zum Schluss, dass Parteien weiterhin traditionell Verbündeten Wählerschaft nachzukkommen, unabhängig von den Veränderungen im Wählerschaftsverhalten & der Sozialstruktur 

** Parties as agents of social representation

Trotz sozio-struktureller Änderungen, politisieren Parteien weiterhin soziale Divisionen durch die Mobilisierung sozial definierter Wählerblocks mit programmatischen Anreizen / appeals 

Die hervorstehende Perspektive auf die soziale Repräsentation ist *sociological* & verwurzelt in der Arbeit von Lipset & Rokkan 
 
- historische & sozio-strukturell definierte Gruppenkonflikte als Ursprung der Ausrichtung zwischen sozialen Gruppen & politischen Parteien 
- programmatische Zuneigung & Parteiverhalten bestimmt durch sozaile Entwicklung & ihre erfolgreiche *bottom-up* Politisierung 

Lipset & Rokkan verfolgen Entwicklung von europäischen Parteisystem zurück bis zu 4 generellen sozial Konflikten verwurzelt in zwei großen Revolutionen des 19. Jh. 

- Konflikte wurden politisiert & führten zu stabilen Ausrichtung zwischen sozial zusammengehörigen Gruppen & politischen Parteien 
  - einerseits die industrielle Revolution, nahm an Arbeiterinteressen im Gegensatz zu den Interessen von Kapitaleignern zu vernachlässigen 
    - Formierung einer sozial demokratischen Partei; führte auch zum Aufsiteg landwirtschaftlicher Parteien
  - andererseits nationale Revolution antagonisiert sekuläre Interessen im Bezug auf föderalen Staat & religiösen Interessen, welche ihre Autonomie sichern wollen 
    - führt zur Etablierung von christlichen Parteien; führt auch zu Konflikt zwischen zentralen Orten & ländlichen Gegenden, welche darauf zielen ihre Werte und Praktiken abzusichern, was zur Bildung von regionalen Parteien führt (Land vs Stadt)
	
Aus sozio-deterministischer Sicht erzwingt Wahlwandel eine Änderung der Parteistrategie 

- Zahl von traditionellen sozialen Gruppen die stabile Wählerkoalitionen konstituiert haben stark gesunken 
- Qualität von Parteienbindung zu sozialen Gruppen verschlechert als Mitgliedschaft in zivilen sozialen Organisatioen sank & die ZUgehörigkeit mit sozialen Gruppen ist unwahrscheinlicher *partisan loyalities* zu bewirken 
- sozio-deterministische Sichtweise geht davon aus, dass Parteien sicht den electoral appeals anpassen, was zu einer sinkenden Neigung von Parteien führt ihrre traditionnelen Unterstützergruppen zu mobilisieren 
  - Parteien können stattdessen zu *catch-all* Strategien wenden, und appeals die abhängig sind von Personalisierung and wertiger Poltik 
  
Im Gegensatz zu der sozio-deterministischen Sichtweise des Parteiverhaltens, gehen Autoren wie Sartori davon aus das Parteien nicht nur die sozialen Phänomene reflektieren, sondern aktiv die kollektiven Interessen und Identitäten bilden 

- Parteien schaffen deliberative Anrezeize um die repräsentative Bindung mit sozial definierten Wählergruppen zu schffen, auch wenn diese Gruppen nicht länger sonderlich zusammenhgehörig sind 
- die Ansicht das Parteien strategisch die sozialen Cleavages betonen oder runterspielen kann wird durch Enyedi hervorgehoben, welcher argumentiert das interpretative Frameworks von politischen Eliten entscheidenden einfluss darauf haben, ob die Unterschiede in den Interessen als soziale Konflikte wahrgenommen werden 

Darlegung soll zeigen, welche der beiden Ansichten über das Parteiverhalten in angesicht sozialstruktureller Änderungen empirisch valide ist 

- Beweise für Veränderung auf Wählerebene, wenig Evidenz über Parteistrategie, um sozio-deterministisches Model des Parteiverhaltens bestätigen oder abweisen zu können 
- to represent distinct social groups and the sparsity(Seltenheit) of empirical evidence, this paper aims to trace patterns of elite-level social representation

** A Text based approach for the Study of social representation

Im Folgenden wird angenommen, dass Parlementarfragen eine nützliche Baseline für die Analyse von den repräsentativen Anstregungen einer Partei abbilden. Eine dictionary based Inhaltsanalyse wird eingeführt, um die programmatischen Stichworte der Parteien erfassen zu können. 

*** Social reprensentation in parliamentary questions

Fragen an die Bundesregierung im Parlament untersucht. Diese Handlungsart dient verschiedenen ZWecken. 

- für legislative Aufsicht, um Informationen über die Handlungen der Regierung zu sammeln und möglicherweise Überschreitungen öffentlich offenzulegen 

Betonung der repräsentativen Funktion von Fragen an den Bundestag (parliamentary questions)

- technisch: Instrument das auf individueller Ebene genutzt werden kann um Legislatoren zu ermöglichen, der Regierung einzelne Fragen zu stellen, welche entweder mündlich in der nächsten Woche beantwortet werden oder in schriftlicher Form ohne weitere Plenardebatten 
- Untersucht werden hier individual-level instruments, eher als Parlamentsreden -> letzteres sind thematisch unbegrenzt durch legislative Agenda, daher bieten sie Einblick into die wahren Prioritäten und repräsentations Brennpunkte einer Partei 
- Fragen an den Bundestag als vergleichbar schwerer Fall, um die Beobachtung des Efforts um der Mobilisierung traditioneller Wählerschaftsgruppen willen, zu gewährleisten 
- Fragen an den Bundestag aus individueller Ebene von Natur aus schwammig, weil jene Individuen Bindungen zu verschiedenen sozialen Gruppen besitzen und somit nicht als Kernbestandteil ihrer Partei angesehen werden können 
- FIndung einer wahrhaftig geteilten Parteiziels um eine partikuläre soziale Gruppe im parlamentarischen Prozess zu repräsentieren benötigt Auffindung einer generellen repräsentativen Profils 
  - Vergleich zu Manifestos: -> Einigung auf kohärente Aussagen möglich, Singale in day to day Aktivitäten kann jedoch stark verschwommen zu dem Manifesto sein 
  
Fragen an den Bundestag für die Analyse stammen vom 17. Bundestag zwischen September 2009 & September 2013 

- 5 Parteien -> CDU/CSU, SPD, FDP, Grüne & Die Linke 
- Regierung gebildet aus konservativer CDU/CSU und ökonomisch liberaler FDP 
- alle Fragen an den Bundestag stammen aus offziellen Parlamentsaufnahmen 
- Merkbare Unterschiede zwischen Regierung & Oppositionspartei 
  - Mitglieder der Regierungspartei fragen weniger häufig
  
*** A dictionary-based approach for the study of social representation

Ziel ist es dictionaries zu generieren, um den Ausmaß mit dem Fragen im Bundestag genutzt werden um Hinweise auf soziale Gruppen beurteilen zu können. Zuerst wird der relevante soziale Konfliktgruppe identifiziert  und die Ausrichtung im deutschen politischen System 

**** Social gropus and alignments in German politics

Lipset & Rokkan: Nicht alle Cleavages sind in jedem Land hervorstechend 

In DE: 

- Ökonomisches Cleavage: Kapitalpol des Cleavages ist ausgerichtet mit CDU/CSU & FDP; Arbeiterseite traditionell repräsentiert durch SPD & neuerdings die Linke 

**Bild Seite 6**

- Kapitalinteressen können in große & kleine bis mittelgroße Unternehmen unterteilt werden 
- Bauern konstituieren dritte ökonomische Interesse mit einzigartigem Set an Interessen 
- Labor pole des ökonomischen Cleavages ist zusammengesetzt aus der Arbeiterbewegung 
- durch ihren Einfluss auf soziale Policies Schaffung werden Wohlfahrts Organisationen als dritte soziale Partner neben den Arbeiterunionen und Arbeiterverbänden wahrgenommen

Religöser Konflikt ist eine zweiter Komflikt innerhalb deutscher Politik 

- charakterisiert durch konfessionelle Unterschiede zwischen der protestantischen Mehrheit & der katholischen Minderheit 
  - Neuerdings unterlag der Konflikt einer Restrukturierung, nun ist es geformt durch die Unterschiede zwischen sekulären Gruppen und den Christlichen Glauben 
- CDU/CSU repräsentieren Christen in Parlamentsangelegenheiten  
- neuer Wertekonflikt im Parteisystem seit 1980ern 
  - wurde manifest während des Aufstiegs der neuen sozialen Bewegung in 1970ern, und führte zur Bildeung der Grüne 
  - postmaterialisitsche Interessen können in quality of lie & selbstverwirklichungs bedenken unterteilt werden

**** Organized interests as indicators for the preferences of social groups

Einführung von Pressemitteilungen der Interessengruppen als mögliche Datenquellen für die systematische Zusammenstellung solcher Behauptungen 

- Möglichkeit verworfen explizie Referenzen über soziale Gruppen zu zählen 
  - solche Analyse würde die Feinheiten politischer Sprache runterspielen & spezfisich die Rolle von Problemen für die soziale Repräsentation 
- Stattdessen nutzt Messstrategie nutzt den Einblick, dass jedes soziale Interesse den organisationellen Ausdruck benötigt um politisch effektiv zu sein
- damit kann eine empirische Analyse der Repräsentation Vorteil von den offenbarten Präferenzen von Organisationen schöpfen, welche als Gruppensorgen relektiert werdne & durch Parteien oder den parlamentarischen Prozess ausgedrückt werden 

The primary challenge for this strategy lies in the selection of organizations as stand-ins for the social groups

- zählen auf korporatistische Natur des deutschen Systems der Interessensvermittlung 
  - in korporatistischen Systemen der Interessenvermittlung  genießen weniger oder nur eine Organisation ein Monopol der Repräsentation durch den Einbezug aller Mitglieder einer spezifischen Gruppe und den priviligierten Zugang zu Entscheidungsschaffungs prozessen durch den Staat
  - dieser Typ der Interessensvermittlung klassisch für Capital-Labor cleavage & religiösen cleavage 
- Daher werden die top tier Verbände welche die subgruppen des kapitals, der arbeit und der religiösen Interessen repräsentieren, ausgewählt 

Organisationen & Interessen 

- Angefangen mit dem Capital pole, der Bundesverband der Deutschen Arbeitgeberverbände BDA & der Bundesverband der Deutschen Industrie BDO handeln gemeinsam im Namen großer Unternehmen. 
- Kleine bis mittelgroße Unternehmen werden durch die Deutsche Industire und Handelskammertag und den Zentralverband des Deutschen Handwerks durch die Mandatskammern repräsentiert 
- Die Interessen der Bauern werden durch den Deutschen Bauernverband repräsentiert 
- Auf der Arbeitsseite dominiert der Deutsche Gewerkschaftsbund mit seinen 8 sokttoralen Unionen der Lohnverhandlungen in Deutschland 
- drei große Schirmorganisationen repräsentieren die Wohlfahrtskomponente des Arbeitspols; der Deutsche Paritätische Wohlfahrtsverband, das Deutsche Rote Kreuz & die Diakonie Deutschland 
- Protestanten im religiös sekulären cleavage werden durch die evangelische Kirche in Deutschland repräsentiert; die katholischen Interessen werden gemeinsam mit durch Deutsche Bischofskonferenz & das Zentralkomitee der Deutschen Katholiken repräsentiert 

Interessensvermittlung in der Wertepolitik is mehr pluralistisch, sodass keine einzelne Organisation identifiziert werden kann die für alle Mitglieder einer sozialen Gruppe sprechen kann. Nichtsdestotrotz existiert eine Organisation auf Bundesebene, mit repräsentativem Monopol für die Interessen der Konsumenten, die Verbraucherzentrale Bundesverband 

Identifizierung der wichtigsten Organisationen für Umweltschützer und Migranteninteresse gestaltet sich schwieriger 

- Im Bezug auf den Umweltschutz werden Daten des Naturschutzbunds Deutschland, BUND, WWF & DNR übernommen 
- durch die religiöse HEterogenität gibt es eine Vielzahl von Migranten & religösen, partikulär Islamischen Organisationen -> Auswahl der Bundesarbeitsgemeinschaft der Immigrantenverbände in Deutschland, die Türkisch-Islamische Union der Anstalt für Religion, ZMD & VIKZ 

Nach der Identifizierung der Referenz Organisationen muss der Typ des zu untersuchenden Textes als Baseline für die Wiedererlangung der Präferenzen von sozialen Gruppen bestimmt werden 

- Auswahl von Pressemitteilungen, da sie weite Sicht auf Gruppenpräferenzen bieten, die kein anderer Typ als Referenzdokument bieten kann 
- Pressemitteilungen bieten eine Mischung aus Staements über Prinzipien & Probleme des Alltags, im Bezug auf Letzteres sind Pressemitteilungen dazu da Einfluss auf die parlamentarischen Angelegenheiten auszuüben 
- daher im Einklang mit den Dynamiken der legislatorischen Agenda & mit Problemen die evtl genannt werden 
- Alle Pressemitteilungen für die ausgewählten Gruppen der Jahre 2009 bis 2013 -> Pressemitteilungen aus ganzen 5 Jahren obwohl Legislatur 4 Jahre hielt 

**** Recovering group-specific demands from press releases

We aim to retrieve terms from the press releases that are most distinctive relative to the press releases of all other organizations

- solche Begriffe sollen die wichtigsten Bedenken ausdrücken & die bedeutungsvollsten Hinweise/Stichworte die mit speziellem Problem in VErbindung gebracht werden können, darlegen 
- Literatur bietet Vorlage im Bezug auf die Erfassung der wichtigsten Begriffe aus den Texten 
  - analysiert ob ein Begriff signifikant häufiger in einem Organisations text corpus, relativ zum Auftreten in Texten aller anderen Organisationen, auftritt 
 
The rows contain the terms that are either identical to a given reference term (tref = 1) or not(tref = 0), the columns contain the two corpuses that are either identical to the reference corpus (cref = 1) or not (cref = 0). The cells contain the term frequencies for a given combination (hi j ), the marginal frequencies are listed in the margins.

To calculate the test statistic, we consider the deviation (Abweichung) of the empirically observed cell frequencies from the expected values, given the marginal distributions. Formally:

The test statistic x^2 is calculated for each term and for each reference corpus to recover the most indicative terms for each organization.

Vor dem Abruf der Dictionaries, werden einige pre & post processing Schritte durchgeführt. Vor der Analyse wird die Liste der Begriffe in den Pressemitteilungen der Organisationen gekürzt, hin zu den Substantiven, da die Substantive am wahrscheinlichsten als Referenz für ein Problem oder ein spezifsches Gruppeninteresse dient 

- dies garantiert, dass die Dictionaries ein Set von Begriffen beinhalten, die bezeichnend/hinweisend wie möglich sind als, policy präferenz
- zusätzlich zu den Pressemitteilungen wird der Inhalt der Plenarprotokolle des Bundestags aus der 17. Legislaturperiode als weiter baseline für den overall text corpus hinzugefügt
  - dies sichert, dass Begriffe im zusammengang mit generellen Parlamentarischen Verfahren die wesentlich häufig in non-reference corpus auftreten, nicht  als hinreichend für eine Referenzgruppe aufgenommen wird 
  
There are 89,709 unique terms with a total of 1,479,164 observations.

- als post processing Schritt werden die Namen, orte & technische fehler von der Liste verworfen 
- es werden die 200 Begriffe mit den höchsten Werden in der test statistik für jede gruppe als benchmark für die representative bindung verwendet 

Um den Ansatz zu validiieren, werden die 20 deutlichsten Begriffe für blue-collar workers dargestellt 

- das Dictionary beinhaltet Begriffe die intuitiv mit Arbeiterinteressen in Verbindung stehen 
  - Begriffe wie Mindestlohn, Leiharbeit, Altersarmut sind enthalten, welche zudem zum Zeitpunkt der Legislatur in der öffentlichen Debatte präsent waren  
  
=> Das selbe für Arbeiter (Dictionary mit Arbeitnehmer, Rente etc) & Frauen 

Zuletzt wird Überlappung der Dictionaries überprüft -> Überlappung vorhanden, dies im Zusammenhang mit soziale Gruppe die zu diesem Cleavage gehört 

Um die soziale Repräsentation zu messen wird die Frequenz mit der die meist indikativen Begriffe in Fragen an den Bundestag genannt werden, gezählt 

- da Interesse an inter-Partei Unterschiede besteht werden alle Fragen der Mitglieder einer Partei als gemeinsamer text corpus behandelt 
  - dies als Messung und nicht als Modelübung wahrgenommen, da kein statistisches model damit verbunden ist  
- einige Worte nicht eindeutig um sie als klare Indikator für eine repräsentative Bindung zu kategorisieren 

Für die folgende Untersuchung, werden die geteilten Referenzen die Parteien um Verbindung mit sozialen Gruppen zu schließen 

Specifically, we calculate the column percentages for each party in order to get a sense of parties’ representational profiles

- dies erlaubt die Balance des Parteiprofils zu analysieren (catch all profil o.ä.)
- erlaubt es die geteilten referenzen zu soziale gruppe der verschiedenen parteien zu vergleichen, um zu erkennen welche Partei am meisten aktiv in der Repräsentation einer Gruppe ist 
- in beiden Fällen wird eine zweistellige Zahl als starke Indikation eines systematisch unterschiedlichen repräsentativen Profils angesehen  
- außerdem wird untersucht welche gruppen generell in Parlamentsangelegenheiten repräsentiert werden 
- im zweiten Schritt wird die Analyse auf Ebene der Cleavage Poles erneut durchgeführt, wo alle Pressemitteilungen durch alle Gruppen in Verbindung mit einem cleavage pole verschmolzen werden um 4 umfassende cleavage dictionaries zu bilden 

*** Parties as agents of social representation

Tabelle 5: 

Zeigt die Frequenz in der beobachtete Referenz einer ausgewählten sozialen Gruppe pro Partei auftritt. Bietet eine Indikation des Ausmaßes zu dem eine Gruppe in Fragen im Bundestag repräsentiert wird 

- einige Gruppen überrepräsentiert, andere kaum (letzteres Frauen & LGBT; aber auch zutreffend für Kirche & Agrarinteressen) 
- im Gegensatz dazu werdne Gruppen im Bezug auf klassen politik häufig genannt; Geschäfts & Arbeiterinteressen belegen mehr als die Hälfte der repräsentativen Bindungen  
- 1/5 der Nennungen mit Umweltschutz Hintergrund 
- This suggests that postmaterialist, value-based groups experience selective representation with environmentalists taking center-stage, while consumers and migrants are trailing behind by large margins.

Importantly, these figures suggest that we are not merely observing the level of corporatist interest intermediation in the various policy fields, but a true difference in representational profiles

Im Bezug auf Partei Spalte sichtbar das drei kleinere Parteien eine vergleichbar exklusive Repräsentation mit starker Betonung auf ihre tradtionellen Unterstützergruppen repräsentieren 

- FDP fokus auf kleine Unternehmen; ähnlich die Linke mit klarer Betonung auf labor pole & Grüne im Bezug auf Umweltgruppe (Grüne überraschend ohne Referenz auf Interesse von Frauen, Migranten oder LGBT Gruppen)

die zwei großen Parteien SPD & CDU/CSU gebrauchen einen eher inklusiven Stil, einen catch all Ansatz zu sozialer Repräsentation -> Klassenkonflikt & Umweltschutz, aber auch klassisch Arbeit über Unternehmensinteresse im Fall der SPD 

- CDU/CSU am meisten balanciert und meisten inklusiv -> somit am ehesten catch all Strategie 
- This observation can be formalized using the Gini coefficient, which provides a systematic measure of the degree to which a set of values is unevenly distributed.

Von Partei zu Gruppenperspektive -> am besten repräsentierte Gruppe durch die Parteien 

- Kapitalinteresse am besten repräsentiert durch FDP 
- Arbeiterinteressen durch SPD & Linke 
- Religion zwar selten erwähnt aber am meisten durch CDU/CSU 
- repräsentations muster für postmaterialisitsche Gruppen gemischt 
  - Umweltinteresse am besten durch Grüne repräsentiert 
  
Tabelle 6: 

Zeigt parteiliche Anstrengungen im Bezug auf übergreifende cleavage pole repräsentation 

- Ergebnisse in Einklang mit a priori Annahmen des Parteiensystems 
- die 3 kleinen PArteien (FDP, Linke, Grüne) haben klaren fokus auf den Interessen in Verbindung mit den traditionellen sozialen Gruppen 
- die Repräsentationsprofile der zwei großen Parteien sind ausbalancierter, aber auch hier sind traditionelle Ausrichtungen erkennbar  

In sum, the findings provide a clear indication for the potential of the proposed text-based method to explore patterns of social representation and for the assumption that the generated dictionaries provide a plausible baseline for recovering the representational efforts of political parties. Substantively, we find that, by and large, parties continue to focus on the social groups they are traditionally aligned with.

*** Conclusion

The previous analysis opens up several avenues for future research. First, we see no reason why the theoretical approach or the measurement strategy should not travel acrosscases. Therefore, it seems worthwhile to bring the approach to a cross-national – and in light of the previous paragraph cross-temporal – comparative design, to identify conditions that might in- or decrease parties’ sustained efforts to consolidate their traditional social ties.

Second, this contribution has investigated parties’ efforts to establish ties with their traditional societal counterparts in non-binding parliamentary speech. We have argued that signaling behavior in the parliamentary arena is a crucial tool for parties to mobilize their support groups. Hence, while analyzing parliamentary speech is important in its own right, it is not obvious how representational ties in parties’ non-binding legislative activities might feed into substantive policy-making when a party enters a government coalition. Future research might employ a similar approach as the one proposed here to assess the degree to which the interests of social groups are reflected in governmental policy.

Third, the present paper has taken an organizational perspective while relying on individual-level data. Although the sum of observations clearly points in the direction of shared efforts, the data might conceal some intra-party heterogeneity. In light of criticism of the unitary actor assumption in party research (Druckman 1996; Laver 1999; Meyer 2012), we aim to move beyond an aggregate-level analysis and treat the individual questions as true individual-level expressions of legislators’ foci of representation in future iterations of this project. This would allow a better understanding of the prerequisites for intra-party pressures to either mobilize of demobilize traditional support groups.

